
import java.awt.HeadlessException;
import javax.swing.JOptionPane;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Connor McNally
 */
public class NewGameMenu extends javax.swing.JFrame {

    //reference to main window
    MineSweeperWindow mainWindow;
    
    public NewGameMenu(MineSweeperWindow w) {
        
        super("Options");
        

        
        mainWindow = w;
        this.setLocation(w.getX() + w.getWidth()/3, w.getY() + w.getHeight()/3);
        this.setResizable(false);
        initComponents();
        
//        try {
//            this.setIconImage(ImageIO.read(new File("Mines.png")));
//        } catch (IOException ex) {
//            Logger.getLogger(MineSweeperWindow.class.getName()).log(Level.SEVERE, null, ex);
//        }
      
        
        
        heightBox.setText(Integer.toString(mainWindow.height));
        widthBox.setText(Integer.toString(mainWindow.width));
        minesBox.setText(Integer.toString(mainWindow.numOfBombs));
        
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        heightBox = new javax.swing.JTextField();
        widthBox = new javax.swing.JTextField();
        minesBox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Height :");

        jLabel3.setText("Width :");

        jLabel4.setText("Number of Mines :");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Custom Difficulty:");

        jLabel6.setText("Difficulty");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Custom Difficulty", "Easy (10 x 10)", "Medium (20 x 20)", "Hard (30 x 30)" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(heightBox)
                                    .addComponent(widthBox)
                                    .addComponent(minesBox)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(heightBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(widthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(minesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        
        try {
            if (Integer.parseInt(minesBox.getText()) < Integer.parseInt(heightBox.getText()) * Integer.parseInt(widthBox.getText()) &&
                   Integer.parseInt(heightBox.getText()) * Integer.parseInt(widthBox.getText()) <= 10000 ) {
                
                mainWindow.height = Integer.parseInt(heightBox.getText());
                mainWindow.width = Integer.parseInt(widthBox.getText());
                mainWindow.numOfBombs = Integer.parseInt(minesBox.getText());
                mainWindow.rebuildMinefield();
                this.dispose();
                
            } else if(Integer.parseInt(minesBox.getText()) >= Integer.parseInt(heightBox.getText()) * Integer.parseInt(widthBox.getText())) {
                
                JOptionPane.showMessageDialog(null, "Error: Number of mines exceeds number of tiles. \nFor current height and "
                        + "width, number of mines must be < " + Integer.parseInt(heightBox.getText()) * Integer.parseInt(widthBox.getText()),
                        "Error", JOptionPane.WARNING_MESSAGE);
                
            } else if(Integer.parseInt(heightBox.getText()) * Integer.parseInt(widthBox.getText()) > 10000){
                
                JOptionPane.showMessageDialog(null,"Height x Width should not exceed 10,000","Error", JOptionPane.WARNING_MESSAGE);
                
            }
        } catch (NumberFormatException e) {
            
            JOptionPane.showMessageDialog(null, "Error: All values must be numerical" ,"Error", JOptionPane.WARNING_MESSAGE);
            
        } 

    }//GEN-LAST:event_jButton1MouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if(jComboBox1.getSelectedItem() == "Easy (10 x 10)"){
            heightBox.setText("10");
            heightBox.setEditable(false);
            
            widthBox.setText("10");
            widthBox.setEditable(false);
            
            minesBox.setText("15");
            minesBox.setEditable(false);
        } else if(jComboBox1.getSelectedItem() == "Medium (20 x 20)" ){
            
            heightBox.setText("20");
            heightBox.setEditable(false);
            
            widthBox.setText("20");
            widthBox.setEditable(false);
            
            minesBox.setText("80");
            minesBox.setEditable(false);
        
        } else if(jComboBox1.getSelectedItem() == "Hard (30 x 30)" ){
            
            heightBox.setText("30");
            heightBox.setEditable(false);
            
            widthBox.setText("30");
            widthBox.setEditable(false);
            
            minesBox.setText("100");
            minesBox.setEditable(false);
        
        } else if(jComboBox1.getSelectedItem() == "Custom Difficulty" ){
            
            heightBox.setEditable(true);
            
            widthBox.setEditable(true);
            
            minesBox.setEditable(true);
            
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField heightBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField minesBox;
    private javax.swing.JTextField widthBox;
    // End of variables declaration//GEN-END:variables
}
